import { sql } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import { char, datetime, index, mysqlTable, uniqueIndex, varchar } from 'drizzle-orm/mysql-core';

// DATETIME stores no zone; every connection pins its session time zone to UTC (see db/client.ts).
const nowUtc = sql`CURRENT_TIMESTAMP(3)`;

// MySQL has no native UUID column type, so identifiers are CHAR(36) generated by the application.
export const users = mysqlTable('users', {
  id: char('id', { length: 36 }).primaryKey().$defaultFn(() => randomUUID()),
  username: varchar('username', { length: 24 }).notNull(),
  email: varchar('email', { length: 255 }).notNull(),
  passwordHash: varchar('password_hash', { length: 255 }).notNull(),
  createdAt: datetime('created_at', { mode: 'date', fsp: 3 }).notNull().default(nowUtc),
  updatedAt: datetime('updated_at', { mode: 'date', fsp: 3 }).notNull().default(nowUtc),
}, (table) => [
  uniqueIndex('users_email_unique').on(table.email),
  uniqueIndex('users_username_unique').on(table.username),
]);

export const sessions = mysqlTable('sessions', {
  id: char('id', { length: 36 }).primaryKey().$defaultFn(() => randomUUID()),
  tokenHash: char('token_hash', { length: 64 }).notNull(),
  userId: char('user_id', { length: 36 }).notNull().references(() => users.id, { onDelete: 'cascade' }),
  createdAt: datetime('created_at', { mode: 'date', fsp: 3 }).notNull().default(nowUtc),
  expiresAt: datetime('expires_at', { mode: 'date', fsp: 3 }).notNull(),
}, (table) => [
  uniqueIndex('sessions_token_hash_unique').on(table.tokenHash),
  index('sessions_user_id_index').on(table.userId),
  index('sessions_expires_at_index').on(table.expiresAt),
]);

export type UserRow = typeof users.$inferSelect;
